#ifndef XFM2_PARAMS_H

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma ide diagnostic ignored "OCUnusedMacroInspection"

// Operator 1
#define PRM_OP1_ALGO                001
#define PRM_OP1_FEEDBACK            007
#define PRM_OP1_SYNC                013
#define PRM_OP1_PHASE               284
#define PRM_OP1_MODE                014
#define PRM_OP1_RATIO               015
#define PRM_OP1_RATIO_FINE          021
#define PRM_OP1_FINE                027
#define PRM_OP1_LEVEL               033
#define PRM_OP1_LEVEL_L             256
#define PRM_OP1_LEVEL_R             257
#define PRM_OP1_VELOCITY_SENS       039
#define PRM_OP1_KEY_BP              045
#define PRM_OP1_KEY_LDEPTH          051
#define PRM_OP1_KEY_RDEPTH          057
#define PRM_OP1_KEY_LCURVE          063
#define PRM_OP1_KEY_RCURVE          069
#define PRM_OP1_L0                  181
#define PRM_OP1_L1                  075
#define PRM_OP1_L2                  082
#define PRM_OP1_L3                  089
#define PRM_OP1_L4                  096
#define PRM_OP1_L5                  193
#define PRM_OP1_DELAY               187
#define PRM_OP1_R1                  103
#define PRM_OP1_R2                  110
#define PRM_OP1_R3                  117
#define PRM_OP1_R4                  124
#define PRM_OP1_R5                  199
#define PRM_OP1_RATE_KEY            140
#define PRM_OP1_EG_LOOP             244
#define PRM_OP1_EG_LOOP_SEG         245
#define PRM_OP1_AMS                 159
#define PRM_OP1_PMS                 222
#define PRM_OP1_WAVE_1              236
#define PRM_OP1_WAVE_2              268
#define PRM_OP1_W_MODE              274
#define PRM_OP1_W_RATIO             280

// Operator 2
#define PRM_OP2_ALGO                002
#define PRM_OP2_FEEDBACK            008
#define PRM_OP2_PHASE               287
#define PRM_OP2_RATIO               016
#define PRM_OP2_RATIO_FINE          022
#define PRM_OP2_FINE                028
#define PRM_OP2_LEVEL               034
#define PRM_OP2_LEVEL_L             258
#define PRM_OP2_LEVEL_R             259
#define PRM_OP2_VELOCITY_SENS       040
#define PRM_OP2_KEY_BP              046
#define PRM_OP2_KEY_LDEPTH          052
#define PRM_OP2_KEY_RDEPTH          058
#define PRM_OP2_KEY_LCURVE          064
#define PRM_OP2_KEY_RCURVE          070
#define PRM_OP2_L0                  182
#define PRM_OP2_L1                  076
#define PRM_OP2_L2                  083
#define PRM_OP2_L3                  090
#define PRM_OP2_L4                  097
#define PRM_OP2_L5                  194
#define PRM_OP2_DELAY               188
#define PRM_OP2_R1                  104
#define PRM_OP2_R2                  111
#define PRM_OP2_R3                  118
#define PRM_OP2_R4                  125
#define PRM_OP2_R5                  200
#define PRM_OP2_RATE_KEY            141
#define PRM_OP2_AMS                 160
#define PRM_OP2_PMS                 223
#define PRM_OP2_WAVE_1              237
#define PRM_OP2_WAVE_2              269
#define PRM_OP2_W_MODE              275
#define PRM_OP2_W_RATIO             281

// Operator 3
#define PRM_OP3_ALGO                003
#define PRM_OP3_FEEDBACK            009
#define PRM_OP3_PHASE               288
#define PRM_OP3_RATIO               017
#define PRM_OP3_RATIO_FINE          023
#define PRM_OP3_FINE                029
#define PRM_OP3_LEVEL               035
#define PRM_OP3_LEVEL_L             260
#define PRM_OP3_LEVEL_R             261
#define PRM_OP3_VELOCITY_SENS       041
#define PRM_OP3_KEY_BP              047
#define PRM_OP3_KEY_LDEPTH          053
#define PRM_OP3_KEY_RDEPTH          059
#define PRM_OP3_KEY_LCURVE          065
#define PRM_OP3_KEY_RCURVE          071
#define PRM_OP3_L0                  183
#define PRM_OP3_L1                  077
#define PRM_OP3_L2                  084
#define PRM_OP3_L3                  091
#define PRM_OP3_L4                  098
#define PRM_OP3_L5                  195
#define PRM_OP3_DELAY               189
#define PRM_OP3_R1                  105
#define PRM_OP3_R2                  112
#define PRM_OP3_R3                  119
#define PRM_OP3_R4                  126
#define PRM_OP3_R5                  201
#define PRM_OP3_RATE_KEY            142
#define PRM_OP3_AMS                 161
#define PRM_OP3_PMS                 224
#define PRM_OP3_WAVE_1              238
#define PRM_OP3_WAVE_2              270
#define PRM_OP3_W_MODE              276
#define PRM_OP3_W_RATIO             282

// Operator 4
#define PRM_OP4_ALGO                004
#define PRM_OP4_FEEDBACK            010
#define PRM_OP4_PHASE               289
#define PRM_OP4_RATIO               018
#define PRM_OP4_RATIO_FINE          024
#define PRM_OP4_FINE                030
#define PRM_OP4_LEVEL               036
#define PRM_OP4_LEVEL_L             262
#define PRM_OP4_LEVEL_R             263
#define PRM_OP4_VELOCITY_SENS       042
#define PRM_OP4_KEY_BP              048
#define PRM_OP4_KEY_LDEPTH          054
#define PRM_OP4_KEY_RDEPTH          060
#define PRM_OP4_KEY_LCURVE          066
#define PRM_OP4_KEY_RCURVE          072
#define PRM_OP4_L0                  184
#define PRM_OP4_L1                  078
#define PRM_OP4_L2                  085
#define PRM_OP4_L3                  092
#define PRM_OP4_L4                  099
#define PRM_OP4_L5                  196
#define PRM_OP4_DELAY               190
#define PRM_OP4_R1                  106
#define PRM_OP4_R2                  113
#define PRM_OP4_R3                  120
#define PRM_OP4_R4                  127
#define PRM_OP4_R5                  202
#define PRM_OP4_RATE_KEY            143
#define PRM_OP4_AMS                 162
#define PRM_OP4_PMS                 225
#define PRM_OP4_WAVE_1              239
#define PRM_OP4_WAVE_2              271
#define PRM_OP4_W_MODE              277
#define PRM_OP4_W_RATIO             283

// Operator 5
#define PRM_OP5_ALGO                005
#define PRM_OP5_FEEDBACK            011
#define PRM_OP5_PHASE               290
#define PRM_OP5_RATIO               019
#define PRM_OP5_RATIO_FINE          025
#define PRM_OP5_FINE                031
#define PRM_OP5_LEVEL               037
#define PRM_OP5_LEVEL_L             264
#define PRM_OP5_LEVEL_R             265
#define PRM_OP5_VELOCITY_SENS       043
#define PRM_OP5_KEY_BP              049
#define PRM_OP5_KEY_LDEPTH          055
#define PRM_OP5_KEY_RDEPTH          061
#define PRM_OP5_KEY_LCURVE          067
#define PRM_OP5_KEY_RCURVE          073
#define PRM_OP5_L0                  185
#define PRM_OP5_L1                  079
#define PRM_OP5_L2                  086
#define PRM_OP5_L3                  093
#define PRM_OP5_L4                  100
#define PRM_OP5_L5                  197
#define PRM_OP5_DELAY               191
#define PRM_OP5_R1                  107
#define PRM_OP5_R2                  114
#define PRM_OP5_R3                  121
#define PRM_OP5_R4                  128
#define PRM_OP5_R5                  203
#define PRM_OP5_RATE_KEY            144
#define PRM_OP5_AMS                 163
#define PRM_OP5_PMS                 226
#define PRM_OP5_WAVE_1              240
#define PRM_OP5_WAVE_2              272
#define PRM_OP5_W_MODE              278
#define PRM_OP5_W_RATIO             284

// Operator 6
#define PRM_OP6_ALGO                006
#define PRM_OP6_FEEDBACK            012
#define PRM_OP6_PHASE               291
#define PRM_OP6_RATIO               020
#define PRM_OP6_RATIO_FINE          026
#define PRM_OP6_FINE                032
#define PRM_OP6_LEVEL               038
#define PRM_OP6_LEVEL_L             266
#define PRM_OP6_LEVEL_R             267
#define PRM_OP6_VELOCITY_SENS       044
#define PRM_OP6_KEY_BP              050
#define PRM_OP6_KEY_LDEPTH          056
#define PRM_OP6_KEY_RDEPTH          062
#define PRM_OP6_KEY_LCURVE          068
#define PRM_OP6_KEY_RCURVE          074
#define PRM_OP6_L0                  186
#define PRM_OP6_L1                  080
#define PRM_OP6_L2                  087
#define PRM_OP6_L3                  094
#define PRM_OP6_L4                  101
#define PRM_OP6_L5                  198
#define PRM_OP6_DELAY               192
#define PRM_OP6_R1                  108
#define PRM_OP6_R2                  115
#define PRM_OP6_R3                  122
#define PRM_OP6_R4                  129
#define PRM_OP6_R5                  204
#define PRM_OP6_RATE_KEY            145
#define PRM_OP6_AMS                 164
#define PRM_OP6_PMS                 227
#define PRM_OP6_WAVE_1              241
#define PRM_OP6_WAVE_2              273
#define PRM_OP6_W_MODE              279
#define PRM_OP6_W_RATIO             285

// Program Pitch EG
#define PRM_PITCH_EG_L0             205
#define PRM_PITCH_EG_L1             130
#define PRM_PITCH_EG_L2             131
#define PRM_PITCH_EG_L3             132
#define PRM_PITCH_EG_L4             133
#define PRM_PITCH_EG_L5             207
#define PRM_PITCH_EG_DLY            206
#define PRM_PITCH_EG_R1             134
#define PRM_PITCH_EG_R2             135
#define PRM_PITCH_EG_R3             136
#define PRM_PITCH_EG_R4             137
#define PRM_PITCH_EG_R5             208
#define PRM_PITCH_EG_RATEKEY        146
#define PRM_PITCH_EG_RANGE          138
#define PRM_PITCH_EG_VELO           139

// Program LFO
#define PRM_LFO_WAVE                153
#define PRM_LFO_SPEED               151
#define PRM_LFO_SYNC                152
#define PRM_LFO_FADE                154
#define PRM_LFO_DEPTH_PITCH         149
#define PRM_LFO_DEPTH_AMP           150

// Program Modulations: Pitch LFO
#define PRM_PITCH_LFO_AFTER         157
#define PRM_PITCH_LFO_WHEEL         155
#define PRM_PITCH_LFO_BREATH        209
#define PRM_PITCH_LFO_FOOT          211

// Program Modulations: Amp LFO
#define PRM_AMP_LFO_AFTER           158
#define PRM_AMP_LFO_WHEEL           156
#define PRM_AMP_LFO_BREATH          210
#define PRM_AMP_LFO_FOOT            212

// Program Modulations: EG Bias
#define PRM_EG_BIAS_AFTER           213
#define PRM_EG_BIAS_WHEEL           214
#define PRM_EG_BIAS_BREATH          215
#define PRM_EG_BIAS_FOOT            216

// Program Modulations: Pitch
#define PRM_PITCH_AFTER             217
#define PRM_PITCH_WHEEL             218
#define PRM_PITCH_BREATH            219
#define PRM_PITCH_FOOT              220

// Program Arpeggiator
#define PRM_ARPEGGIATOR_MODE        450
#define PRM_ARPEGGIATOR_TEMPO       451
#define PRM_ARPEGGIATOR_MUL         453
#define PRM_ARPEGGIATOR_OCTAVES     454

// Program Perf Controls
#define PRM_CTL_1H                  420
#define PRM_CTL_1L                  421
#define PRM_CTL_2H                  422
#define PRM_CTL_2L                  423
#define PRM_CTL_3H                  424
#define PRM_CTL_3L                  425
#define PRM_CTL_4H                  426
#define PRM_CTL_4L                  427

// Program Other
#define PRM_OTHER_BEND_UP           172
#define PRM_OTHER_BEND_DOWN         173
#define PRM_OTHER_TRANSPOSE         174
#define PRM_OTHER_VOLUME            180
#define PRM_OTHER_PAN               221
#define PRM_OTHER_VELOCITY_OFFSET   242
#define PRM_OTHER_EG_RESTART        246
#define PRM_OTHER_LEGATO            228
#define PRM_OTHER_PORTA_MODE        229
#define PRM_OTHER_PORTA_TIME        230
#define PRM_OTHER_TUNING            251
#define PRM_OTHER_OUTPUT            411

// Program Effects
#define PRM_FX_BITCRUSHER_DEPTH     380
#define PRM_FX_DECIMATOR_DEPTH      370
#define PRM_FX_FILTER_LO            320
#define PRM_FX_FILTER_HI            321
#define PRM_FX_CHORFLNG_DRY         360
#define PRM_FX_CHORFLNG_WET         361
#define PRM_FX_CHORFLNG_MODE        362
#define PRM_FX_CHORFLNG_SPEED       363
#define PRM_FX_CHORFLNG_DEPTH       364
#define PRM_FX_CHORFLNG_FEEDBACK    365
#define PRM_FX_CHORFLNG_LRPHASE     366
#define PRM_FX_PHASER_DRY           310
#define PRM_FX_PHASER_WET           311
#define PRM_FX_PHASER_MODE          312
#define PRM_FX_PHASER_SPEED         314
#define PRM_FX_PHASER_DEPTH         313
#define PRM_FX_PHASER_FEEDBACK      315
#define PRM_FX_PHASER_OFFSET        316
#define PRM_FX_PHASER_STAGES        317
#define PRM_FX_PHASER_LRPHASE       318
#define PRM_FX_AM_DEPTH             332
#define PRM_FX_AM_SPEED             330
#define PRM_FX_AM_RANGE             331
#define PRM_FX_AM_LRPHASE           333
#define PRM_FX_DELAY_DRY            300
#define PRM_FX_DELAY_WET            301
#define PRM_FX_DELAY_MODE           302
#define PRM_FX_DELAY_TIME           303
#define PRM_FX_DELAY_FEEDBACK       304
#define PRM_FX_DELAY_LO             305
#define PRM_FX_DELAY_HI             306
#define PRM_FX_DELAY_TEMPO          307
#define PRM_FX_DELAY_MUL            308
#define PRM_FX_DELAY_DIV            309
#define PRM_FX_ROUTING              410
#define PRM_FX_REVERB_DRY           390
#define PRM_FX_REVERB_WET           391
#define PRM_FX_REVERB_MODE          392
#define PRM_FX_REVERB_DECAY         393
#define PRM_FX_REVERB_DAMP          394

#pragma clang diagnostic pop

#endif

